"""Add column changed

Revision ID: e4c688567c95
Revises: 0ddbf54f1b06
Create Date: 2023-09-29 19:47:44.942744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c688567c95'
down_revision = '0ddbf54f1b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed', sa.Integer(), nullable=True))

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('changed')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('changed')

    # ### end Alembic commands ###
